# What standard to use. This is optional and defaults to VHDL2008.
standard = "2008"

# File names are either absolute or relative to the parent folder of the vhdl_ls.toml file
[libraries]

TVL.files = [
  'tvl_lib/lib/*.vhdl'
]

defaultlib.files = [
    "rtl_designs/**/*.vhdl",
  "tvl_lib/testbench/**/*.vhdl"
]

vunit_lib.files = [
    "vunit_vhdl_src/**/*.vhd",
]
vunit_lib.exclude = [
    "vunit_vhdl_src/**/*93*",
    "vunit_vhdl_src/**/*2019*",
    "vunit_vhdl_src/**/*2002*",
    "vunit_vhdl_src/**/run.py",
    "vunit_vhdl_src/**/test/*",
    "vunit_vhdl_src/osvvm/*"
]

osvvm.files = [
    "vunit_vhdl_src/osvvm/**/*.vhd"
]

osvvm.exclude = [
    "vunit_vhdl_src/osvvm/**/demo/*"
]