# File names are either absolute or relative to the parent folder of the
# vhdl_ls.toml file and supports glob-style patterns.

[libraries]

# Defines library TVL
TVL.files = [
  'tvl_lib\lib\*.vhdl'
]